"""
Repository layer for financial news operations.

Repositories isolate:
- database queries
- ORM logic
- persistence operations

Benefits:
- reusable DB access
- cleaner services
- easier testing
- better architecture separation
"""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from apps.db.models.news_article import NewsArticle
from apps.schemas.news import NewsArticleCreate


class NewsRepository:
    """
    Repository for financial news operations.
    """

    def __init__(self, db: AsyncSession):
        """
        Repository initialized with async DB session.
        """

        self.db = db

    async def create_article(
        self,
        payload: NewsArticleCreate,
    ) -> NewsArticle:
        """
        Create new financial news article.
        """

        article = NewsArticle(
            title=payload.title,
            source=payload.source,
            content=payload.content,
        )

        # Add ORM object to transaction
        self.db.add(article)

        # Commit transaction
        await self.db.commit()

        # Refresh ORM object with DB generated values
        # Example:
        # autogenerated ID
        # timestamps
        await self.db.refresh(article)

        return article

    async def get_article_by_id(
        self,
        article_id: int,
    ) -> NewsArticle | None:
        """
        Retrieve article by primary key.
        """

        query = select(NewsArticle).where(NewsArticle.id == article_id)

        result = await self.db.execute(query)

        return result.scalar_one_or_none()

    async def get_all_articles(
        self,
    ) -> list[NewsArticle]:
        """
        Retrieve all financial news articles.
        """

        query = select(NewsArticle).order_by(NewsArticle.created_at.desc())

        result = await self.db.execute(query)

        return list(result.scalars().all())
