"""add article metadata fields

Revision ID: 2d1ab43a1889
Revises: 653a0a22bb5a
Create Date: 2026-05-26 21:45:58.289438

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d1ab43a1889"
down_revision: str | Sequence[str] | None = "653a0a22bb5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_articles",
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "news_articles", sa.Column("article_url", sa.String(length=1000), nullable=True)
    )
    op.create_unique_constraint(None, "news_articles", ["article_url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "news_articles", type_="unique")
    op.drop_column("news_articles", "article_url")
    op.drop_column("news_articles", "published_at")
    # ### end Alembic commands ###
