"""add sentiment fields

Revision ID: 7e20a94eae67
Revises: 10bc0c511c44
Create Date: 2026-06-08 00:40:31.743438

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e20a94eae67"
down_revision: str | Sequence[str] | None = "10bc0c511c44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_articles", sa.Column("sentiment", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "news_articles", sa.Column("sentiment_score", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_articles", "sentiment_score")
    op.drop_column("news_articles", "sentiment")
    # ### end Alembic commands ###
